### ISSUE TITLE
Plugin Usage / Status?

### ISSUE THREAD

**Issue by dsully** [dubocr/homebridge-sun-protect#1]
Hi - I'm interested in what you have here. Is the plan to allow opening & closing of shades (window coverings) ?

Thanks

**Comment by dubocr** [comment]
Hi,

Yes, this is a shortcut to execute shades automation depending of sun position. I push the README juste now.
It is not documented yet but here is an example config : 

{
  "accessory": "SunProtect",
  "name": "Soleil",
  "location": {
	  "lat": 46.491670,
	  "long": -1.766296
  },
  "triggers": [
	  {
		  "name": "Etage - SE",
		  "azimuthMin": 80,
		  "azimuthMax": 240,
		  "altitudeMin": 0
	  },
	  {
		  "name": "Cuisine",
		  "azimuthMin": 95,
		  "azimuthMax": 240,
		  "altitudeMin": 20
	  },
	  {
		  "name": "Salon",
		  "azimuthMin": 150,
		  "azimuthMax": 260,
		  "altitudeMin": 10
	  },
	  {
		  "name": "Suite",
		  "azimuthMin": 150,
		  "azimuthMax": 285,
		  "altitudeMin": 15
	  },
	  {
		  "name": "Etage - SO",
		  "azimuthMin": 170,
		  "azimuthMax": 275,
		  "altitudeMin": 5
	  }
  ]
  }

**Comment by dsully** [comment]
Thanks! I'll play around with this.
